GET http://localhost:8000/member/member/count
Accept: application/json

###

GET http://localhost:8000/member/member/insert
Accept: application/json

###

GET http://localhost:8000/member/member/delete
Accept: application/json

###
POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13720239041

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13935846384

###

POST http://localhost:8000/member/member/sendCode
Content-Type: application/x-www-form-urlencoded

mobile=13720239041