POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "memberId" : "1",
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}

###

POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}

###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile" : "13720239041",
  "code" : 8888
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("token", response.body.content.token);
%}

###

POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}
