POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "memberId" : "1",
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}

###

POST http://localhost:8001/member/passenger/save
Content-Type: application/json

{
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}

###

POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile" : "13720239041",
  "code" : 8888
}

> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.content.token));
client.global.set("token", response.body.content.token);
%}

###

POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name" : "逯晓琪",
  "idCard": "1231231231321313",
  "type": "3"
}

###

GET http://localhost:8000/member/passenger/queryList
Accept: application/json
token: {{token}}

###

GET http://localhost:8000/member/passenger/queryList?page=1&size=3
Accept: application/json
token: {{token}}

###

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id" : 1768183915366977536,
  "memberId":1766666339369488384,
  "name" : "逯晓琪",
  "idCard": "1234567890",
  "type": "3",
  "createTime": "2024-03-14 17:30:00"
}