###

GET http://localhost:8000/business/admin/trainStation/query-list?page=1&size=3
Accept: application/json
token: {{token}}

###

GET http://localhost:8000/business/admin/train/query-all
Accept: application/json

###


GET http://localhost:8000/business/admin/daily-train/generate-daily/2024-04-06
Accept: application/json

###